# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
sphinx:
  configuration: docs/conf.py
  # disable this for more lenient docs builds
  fail_on_warning: true

commands:
  - command: sphinx-apidoc -F -o ./docs/docu src
  - type: before_build
