name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [labeled, opened, synchronize, reopened]
  workflow_dispatch:
  merge_group:
    types: [checks_requested]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  test:
    name: Test
    permissions:
      contents: read
      pull-requests: write
    secrets: inherit
    uses: ./.github/workflows/test.yaml

  build:
    name: Build
    permissions:
      contents: read
      pull-requests: write
    secrets: inherit
    uses: ./.github/workflows/build.yaml

  # upload_coverage:
  #   needs: [test]
  #   name: Upload Coverage
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout ${{github.repository }}
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Download Coverage Artifact
  #       uses: actions/download-artifact@v4
  #       # if `name` is not specified, all artifacts are downloaded.

  #     - name: Upload Coverage to Coveralls
  #       uses: coverallsapp/github-action@v2
  #       with:
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         format: lcov
