name: docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-name: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[doc]
    - name: Generate API documentation
      run: |
        sphinx-apidoc -F -o ./docs/docu src
    - name: Build documentation
      run: |
        sphinx-build -E docs ./docs/build
# action checks if the documentation builds, build and deployment handled in readthedocs.yaml